### ISSUE TITLE
Too many spots for code execution

### ISSUE THREAD

**Issue by Lvl4Sword** [GianisTsol/python-p2p#2]
https://github.com/GianisTsol/python-p2p/blob/master/p2pnetwork/node.py#L285 is one such spot.
Wrapping something in str() is not a way to sanitize input or prevent code execution.

**Comment by GianisTsol** [comment]
My code isn't optimized for security. It's just a simple prototype. You can open a pull request with a fix if you want. Thank you for helping!!
