### ISSUE TITLE
pycrypto depricated

### ISSUE THREAD

**Issue by PCM1945** [GianisTsol/python-p2p#7]
on python 3.10.1 crypto lib cannot be installed deprecated lib warning was showed 
[depricated log.txt](https://github.com/GianisTsol/python-p2p/files/9924997/depricated.log.txt)

**Comment by GianisTsol** [comment]
> on python 3.10.1 crypto lib cannot be installed deprecated lib warning was showed [depricated log.txt](https://github.com/GianisTsol/python-p2p/files/9924997/depricated.log.txt)

The project uses `pycryptodome`. `pycrypto` is deprecated and should not be used. Try installing the dependencies using `setup.py` as shown in the README and the correct package will be installed.
